server:
  port: 8088

management:
  server:
    port: 8099
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - uk.gov.justice.laa.crime.applications.adaptor.exception.RetryableWebClientResponseException
          - org.springframework.web.reactive.function.client.WebClientRequestException

    instances:
      callCrimeApplyDatastore:
        base-config: default

services:
  maat-api:
    oAuthEnabled: true
    baseUrl: ${MAAT_API_BASE_URL}

  crime-apply-api:
    baseUrl: ${CRIME_APPLY_API_URL}
    clientSecret: ${CRIME_APPLY_API_AUTH_SECRET}
    issuer: ${CRIME_APPLY_AUTH_KEY_ISSUER}
