# Default values for laa-crime-applications-adaptor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-crime-applications-adaptor-dev-ecr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

sentry:
  sampleRate: 0.05

aws_region: eu-west-2

java:
  host_env: test

maatApi:
  baseUrl: https://laa-maat-data-api-test.apps.live.cloud-platform.service.justice.gov.uk/api
  oauthUrl: https://maat-api-test.auth.eu-west-2.amazoncognito.com/oauth2/token
  registrationId: maatapi
  oauthScope: maat-api-test/standard

crimeApplyApi:
  baseUrl: https://laa-crime-apply-mock-api-test.apps.live.cloud-platform.service.justice.gov.uk/api/v1/maat/applications
  issuer: maat-adapter-test

crimeApplicationAdaptor:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_EQEoa8Ma5

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "crime-applications-adaptor"

service:
  type: ClusterIP
  port: 8088

ingress:
  environmentName: laa-crime-applications-adaptor-test
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-apps-team"
  externalAnnotations: {}
  internalHost:
    host: laa-crime-applications-adaptor-test.apps.live.cloud-platform.service.justice.gov.uk
    path: /api
  externalHost:
    host: laa-crime-applications-adaptor-test.apps.live.cloud-platform.service.justice.gov.uk
    paths:
      swaggerPath: /swagger-ui
      openApiPath: /api-docs
  tls: []
  className: modsec

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8099
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
